version: "2"
services:
    accession:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        environment:
            SERVICE_NAME: accession
            VIRTUAL_BACKEND: api
            VIRTUAL_PATH: /accession
            VIRTUAL_PORT: 80
    requisition:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        environment:
            SERVICE_NAME: requisition
            VIRTUAL_BACKEND: api
            VIRTUAL_PATH: /requisition
            VIRTUAL_PORT: 80
    root:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        environment:
            SERVICE_NAME: root_service
            VIRTUAL_BACKEND: api
            VIRTUAL_PATH: /
            VIRTUAL_PORT: 80
    router:
        build: .
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
